---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-api-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-number-api
  template:
    metadata:
      labels:
        app: random-number-api
    spec:
      containers:
        - name: random-number-api
          image: waisahmadi0907/random-number-api:v1
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-client-deployment
spec:
  selector:
    matchLabels:
      app: random-number-client
  template:
    metadata:
      labels:
        app: random-number-client
    spec:
      - name: random-number-client
        image: waisahmadi0907/random-client:v1
        ports:
          - containerPort: 5000
