---
apiVersion: v1
kind: Service
metadata:
  name: random-number-api-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: random-number-api
  ports:
    - port: 80
      targetPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: random-number-client-svc
  namespace: default
spec:
  selector:
    app: random-number-client
  ports:
    - port: 8080
      targetPort: 5000
  type: LoadBalancer
