- name: Install WireGuard
  apt:
    name: wireguard
    update_cache: yes

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Generate keys
  shell: wg genkey
  register: server_private

- shell: echo "{{ server_private.stdout }}" | wg pubkey
  register: server_public

- shell: wg genkey
  register: client_private

- shell: echo "{{ client_private.stdout }}" | wg pubkey
  register: client_public

- name: Server config
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
  notify: restart wg

- name: Enable WG
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Client config
  template:
    src: client.conf.j2
    dest: /home/ubuntu/client.conf

